import {
  Clapperboard,
  Cuboid,
  Film,
  Image,
  Palette,
  MonitorSmartphone,
  Sparkles,
} from "lucide-react";
// import { ChevronLeft, ChevronRight } from "lucide-react";

export const categories = [
  { name: "All", icon: Clapperboard },
  { name: "Video Edits", icon: Film },
  { name: "Motion Graphics", icon: Sparkles },
  { name: "3D", icon: Cuboid },
  { name: "2D", icon: Clapperboard },
  { name: "VFX", icon: Sparkles },
  { name: "Photo Manipulation", icon: Image },
  { name: "Graphic Designs", icon: Palette },
  { name: "UI/UX", icon: MonitorSmartphone },
];

export const projects = [
  {
    id: 1,
    title: "",
    subtitle: "Cinematic brand film",
    category: "3D",
    image: "/assets/Projects/image1.jpg",
    accent: "#60E6C1",
    year: "2026",
    duration: "01:24",
    format: "4K",
    featured: true,
    type: "image",

    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 2,
    title: "Y2K Poster",
    subtitle: "Y2k Weeknd Poster",
    category: "Graphic Designs",
    image: "/assets/Projects/y2kweeknd.png",
    accent: "#7BD7FF",
    year: "2026",
    duration: "00:45",
    format: "4K",
    featured: false,
    type: "image",
  },
  {
    id: 3,
    title: "Aura / Form",
    subtitle: "Luxury product visualization",
    category: "Photo Manipulation",
    image: "/assets/Projects/image2.jpg",
    accent: "#FFB66B",
    year: "2025",
    duration: "00:30",
    format: "CGI",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 4,
    title: "Signal / Noise",
    subtitle: "Editorial title treatment",
    category: "3D",
    image: "/assets/Projects/image3.jpg",
    accent: "#C99BFF",
    year: "2025",
    duration: "00:38",
    format: "2K",
    featured: false,
    type: "image",
    addon: {
      available: true,
      assetId: "b1",
    },
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 5,
    title: "Little Orbit",
    subtitle: "Character animation short",
    category: "3D",
    image: "/assets/Projects/image4.jpg",
    accent: "#FFD166",
    year: "2025",
    duration: "01:12",
    format: "HD",
    featured: false,
    type: "image",
     addon: {
      available: true,
      assetId: "b2",
    },
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },

  {
    id: 7,
    title: "Chromatic Bloom",
    subtitle: "Abstract visual identity",
    category: "Graphic Designs",
    image: "/assets/Projects/image6.png",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 8,
    title: "Cyber glitch",
    subtitle: "Cyber glitch",
    category: "VFX",
    image: "/assets/Projects/image7.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/XqMJu_VdJM4?si=KC1BQ66x3npG7Fla",
  },
  {
    id: 9,
    title: "konkrët",
    subtitle: "konkrët",
    category: "VFX",
    image: "/assets/Projects/image8.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/8C0op1dXdec?is=pUpbfu_SGwXJlQ7M",
  },
  {
    id: 10,
    title: "Obi-wan kenobi scene recreated",
    subtitle: "Obi-wan kenobi scene recreated",
    category: "VFX",
    image: "/assets/Projects/image9.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/MVvjsDDOjpw?is=ZS-C0mnXEzwYOzG3",
  },
  {
    id: 12,
    title: "Obi-wan kenobi scene recreated",
    subtitle: "Obi-wan kenobi scene recreated",
    category: "Video Edits",
    image: "/assets/Projects/image10.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/fSWKJpSQKjE",
  },
  {
    id: 12,
    title: "Obi-wan kenobi scene recreated",
    subtitle: "Obi-wan kenobi scene recreated",
    category: "3D",
    image: "/assets/Projects/image11.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "image",
    videoUrl: "",
  },
  {
    id: 13,
    title: "Obi-wan kenobi scene recreated",
    subtitle: "Obi-wan kenobi scene recreated",
    category: "Motion Graphics",
    image: "/assets/Projects/image12.jpeg",
    accent: "#78F0A5",
    year: "2024",
    duration: "00:28",
    format: "HD",
    featured: false,
    type: "video",
    videoUrl: "https://www.youtube.com/shorts/Vi555TCYzOk?is=hrbkJLXq4rlyYZ7W",
  },
  {
    id: 14,
    title: "Signal / Noise",
    subtitle: "Editorial title treatment",
    category: "3D",
    image: "/assets/Projects/image13.jpg",
    accent: "#C99BFF",
    year: "2025",
    duration: "00:38",
    format: "2K",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
];

export const assetData = [
  // Blender assets
  {
    id: "b1",
    name: "Cyber city",
    extension: ".blend",
    software: "Blender",
    year: "2026",
    downloadLink: "https://t.me/triplevisionaryarchive/13",
  },

];

export const softwareList = [
  "All",
  "Blender",
  "After Effects",
  "Premiere Pro",
  "Fusion",
  "Photoshop",
  "GIMP",
  "Inkscape",
  "Illustrator",
  "Natron",
  "Kdenlive",
  ".fbx",
  ".obj",
  ".png",
  ".exr",
  ".jpeg",
  ".tiff",
];
